#!/bin/bash

PUBLIC_IP=$(oc-metadata --cached PUBLIC_IP_ADDRESS)

cat <<EOF
Hi Cloud Rider,
Welcome to the Yunohost image!
Initialize Yunohost at http://${PUBLIC_IP}.
You can also run "yunohost tools postinstall" in the command-line.
Visit the Yunohost homepage for more information: https://yunohost.org
Enjoy!
EOF
